Add fsgroup for IAM credentials files
astronomer/airflow-chart pull request #187
Opened 2021-02-12 21:52 UTC by rbankston

## Description

Add fsGroup to the Kubernetes Pod Template definition. The current pod operator template overrides any template from the airflow image and if an IAM credential exists it won't be added with the proper ownership causing issues with it being accessed by the pod

## 🎟 Issue(s)

Resolves astronomer/issues#2587

## 📋 Checklist

- [x] The PR title is informative to the user experience

2021-02-16 23:25 UTC, rbankston commented
@jpweber @dimberman @andriisoldatenko can you folks take a look at this for me?

2021-02-22 16:37 UTC, ianstanton commented
Taking a look

2021-02-22 16:43 UTC, jpweber approved these changes

2021-02-22 16:44 UTC, ianstanton requested changes
Thanks @rbankston! Can we add `fsGroup` as a top level value? This will give the user the option to supply their own value. We can default to `.Values.gid` and use `.Values.fsGroup` if it exists. We can also add this option to the Celery worker deployment. What do you think? cc @ben-astro

2021-02-22 19:38 UTC, rbankston commented
@ianstanton https://github.com/astronomer/airflow-chart/blob/83856c33ef059ba44d022fa6b5c737d1db0eafcd/templates/workers/worker-deployment.yaml#L65 and https://github.com/astronomer/airflow-chart/blob/5934a9ce1c19f44f5067fba205b119d43df6030b/templates/scheduler/scheduler-deployment.yaml#L75 already use that value as the fsGroup by default

2021-02-23 12:18 UTC, ianstanton commented
@rbankston I guess I was thinking of adding `fsGroup: ~` to `values.yaml` and then using something like `fsGroup: {{ (default .Values.gid .Values.fsGroup }}` in case the user wanted to supply their own value for `fsGroup`. 

Do you think there will ever be a case where a user would want to supply their own value?

2021-02-23 16:31 UTC, rbankston commented
@ianstanton not 100% sure how Astronomer Certified folks would use that but don't believe today that Astronomer Enterprise folks can change the user of the pod easily.

2021-02-23 17:04 UTC, ianstanton commented
@rbankston Okay! we can leave it like this and revisit if the topic comes up again.

2021-02-23 17:04 UTC, ianstanton approved these changes

2021-02-25 19:04 UTC, kaxil commented
@danielhoherd the test is failing with:

```
bin/package-and-release-internal: line 16: GCP_TOKEN: unbound variable
```

Does it ring any bells?

2021-03-01 21:35 UTC, rbankston commented
Closing this pull request because of the way it was created. Same PR was merged in https://github.com/astronomer/airflow-chart/pull/190

2021-03-01 21:35 UTC, closed without merging