Add extra volumes and volume mounts on scheduler/workers
astronomer/airflow-chart pull request #193
Opened 2021-03-17 15:34 UTC by jedcunningham

Add support for extra volumes and volume mounts in scheduler, celery workers, and kubernetes executor workers.

## Description
Add

## 🎟 Issue(s)

Resolves astronomer/issues#2684
Resolves astronomer/issues#2685 (in coordination with #192)

Co-authored-by: Daniel Imberman <daniel.imberman@gmail.com>

2021-03-17 15:46 UTC, kaxil approved these changes

2021-03-17 23:19 UTC, ianstanton requested changes
Some nitpicks

2021-03-17 23:19 UTC, ianstanton commented on tests/pod-template-file_test.yaml
> +            mountPath: /opt/test
```suggestion
            mountPath: /opt/test

```

2021-03-17 23:19 UTC, ianstanton commented on tests/scheduler_scheduler-deployment_test.yaml
> +            mountPath: /opt/test
```suggestion
            mountPath: /opt/test

```

2021-03-17 23:19 UTC, ianstanton commented on tests/workers_worker-deployment_test.yaml
> +            mountPath: /opt/test
```suggestion
            mountPath: /opt/test

```

2021-03-19 13:56 UTC, ianstanton approved these changes

2021-03-19 23:03 UTC, jedcunningham commented
Take another look @kaxil @ianstanton, I've added `extraObjects`.

2021-03-22 13:11 UTC, ianstanton approved these changes

2021-03-22 14:04 UTC, jedcunningham commented on templates/extra-objects.yaml
> +{{ end }}
I think it covers the common cases. I'll link out to this in the docs.

2021-03-24 00:20 UTC, kaxil approved these changes

2021-03-24 00:22 UTC, merged